[tool.poetry]
name = "entropy-news"
version = "0.1.0"
description = "Entropy of Financial News using LSTM based on 'New News is Bad News' methodology."
authors = ["Diogo Ribeiro (DiogoRibeiro7) <dfr@esmad.ipp.pt>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "entropy_news" }]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0"
tqdm = "^4.66"
numpy = "^1.25"

[tool.poetry.group.torch.dependencies]
torch = "^2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"
pytest-cov = "^4.1"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.0"
myst-parser = "^2.0"
sphinx-rtd-theme = "^2.0"

[tool.poetry.scripts]
entropy-news-train = "entropy_news.main:main"
entropy-news-forecast = "entropy_news.main_forecast:main"
entropy-news-rolling = "entropy_news.rolling_train_forecast:main"
entropy-news-eval = "entropy_news.main_evaluate:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
