[tool.poetry]
name = "entropy-news"
version = "0.1.0"
description = "Entropy of Financial News using LSTM based on 'New News is Bad News' methodology."
authors = ["Diogo Ribeiro <diogo_dj@hotmail.com>"]
readme = "README.md"
packages = [{ include = "entropy_news" }]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.0"
pandas = "^2.0"
scikit-learn = "^1.3"
tqdm = "^4.66"
numpy = "^1.25"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"

[tool.poetry.scripts]
entropy-news-train = "entropy_news.main:main"
entropy-news-forecast = "entropy_news.main_forecast:main"
entropy-news-rolling = "entropy_news.rolling_train_forecast:rolling_pipeline"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
